
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[build]
  # This will be run the site build
  command = "npm run build"
  # This is the directory is publishing to netlify's CDN
  # functions build directory
  functions = "build-functions"

[dev]
  # functions build directory
  functions = "functions"